name: Push Docker Image to ECR

on:
  push:
    branches:
      - master  # Apni main branch ka naam yahan dal do

jobs:
  push_to_ecr:
    name: Build & Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com

    - name: Build and Tag Docker Image
      run: |
        IMAGE_TAG=${{ github.run_number }}  # GitHub pipeline number
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        docker pull wordpress:latest

    - name: Push Docker Image to ECR
      run: |
        docker tag wordpress:latest ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPOSITORY }}:latest
        docker push ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPOSITORY }}:latest
